export const menuItems = [
    {
        id: 1,
        category: "platos",
        subcategory: "Parrilladas",
        name: "Carne asada y pechuga dobada",
        price: 295,        
        img: "../assets/images/menu/platos01.png",
    },
    {
        id: 2,
        category: "platos",
        subcategory: "Parrilladas",
        name: "Arrachera y pechuga adobada",
        price: 385,        
        img: "../assets/images/menu/platos02.png",
    },
    {
        id: 3,
        category: "platos",
        subcategory: "Parrilladas",
        name: "Picaña en costra de rub de café",
        price: 450,        
        img: "../assets/images/menu/platos03.png",
    },
    {
        id: 4,
        category: "platos",
        subcategory: "Parrilladas",
        name: "Pechuga adobada",
        price: 235,        
        img: "../assets/images/menu/platos04.png",
    },
    {
        id: 5,
        category: "platos",
        subcategory: "Parrilladas",
        name: "Arrachera",
        price: 435,        
        img: "../assets/images/menu/platos05.png",
    },
    {
        id: 6,
        category: "platos",
        subcategory: "Diezmillo con queso fundido",
        name: "Arrachera",
        price: 395,        
        img: "../assets/images/menu/platos06.png",
    },
    {
        id: 7,
        category: "platos",
        subcategory: "Parrilladas",
        name: "Carne asada",
        price: 365,        
        img: "../assets/images/menu/platos07.png",
    },
    {
        id: 8,
        category: "platos",
        subcategory: "Especialidades NG para compartir",
        name: "New York con chorizo español",
        price: 580,        
        img: "../assets/images/menu/platos08.png",
    },
    {
        id: 9,
        category: "platos",
        subcategory: "Especialidades NG para compartir",
        name: "Rib Eye Cowboy en cama de tuétanos",
        price: 550,        
        img: "../assets/images/menu/platos09.png",
    },
    {
        id: 10,
        category: "platos",
        subcategory: "Especialidades NG para compartir",
        name: "Short Rib con papas al horno",
        price: 525,        
        img: "../assets/images/menu/platos10.png",
    },
    {
        id: 11,
        category: "bebidas",
        subcategory: "Bebidas",
        name: "Tropical NG",
        price: 98,        
        img: "../assets/images/menu/bebidas01.jpg",
    },
    {
        id: 12,
        category: "bebidas",
        subcategory: "Bebidas",
        name: "Ocean NG",
        price: 109,        
        img: "../assets/images/menu/bebidas02.png",
    },
    {
        id: 13,
        category: "bebidas",
        subcategory: "Bebidas",
        name: "Vampiro",
        price: 89,        
        img: "../assets/images/menu/bebidas03.png",
    },
    {
        id: 14,
        category: "bebidas",
        subcategory: "Bebidas",
        name: "Mojito Maracuyá",
        price: 109,        
        img: "../assets/images/menu/bebidas04.png",
    },
    {
        id: 15,
        category: "bebidas",
        subcategory: "Bebidas",
        name: "Amor Negro",
        price: 105,        
        img: "../assets/images/menu/bebidas05.png",
    },
    {
        id: 16,
        category: "bebidas",
        subcategory: "Bebidas",
        name: "Caballero Negro",
        price: 109,        
        img: "../assets/images/menu/bebidas06.png",
    },
    {
        id: 17,
        category: "bebidas",
        subcategory: "Cervezas",
        name: "Cerveza: Heineken, Tecate, Indio y otros",
        price: 45,        
        img: "../assets/images/menu/bebidas07.png",
    },
    {
        id: 18,
        category: "bebidas",
        subcategory: "Cervezas",
        name: "Cerveza: Amstel Ultra, Strongbow",
        price: 55,        
        img: "../assets/images/menu/bebidas08.png",
    },
    {
        id: 19,
        category: "bebidas",
        subcategory: "Cervezas",
        name: "Cerveza: XX Ambar, XX Larger",
        price: 49,        
        img: "../assets/images/menu/bebidas09.png",
    },
    {
        id: 20,
        category: "bebidas",
        subcategory: "Cervezas",
        name: "Cerveza artesanal",
        price: 59,        
        img: "../assets/images/menu/bebidas10.png",
    },
    {
        id: 21,
        category: "bebidas",
        subcategory: "Bebidas",
        name: "Bebidas",
        price: "Desde $19",        
        img: "../assets/images/menu/bebidas11.png",
    },
    {
        id: 22,
        category: "bebidas",
        subcategory: "Vinos",
        name: "Vinos",
        price: "Desde $100",        
        img: "../assets/images/menu/bebidas12.png",
    },
    {
        id: 23,
        category: "postres",
        subcategory: "Postres",
        name: "Pan de elote con gloria derretida",
        price: "$95",        
        img: "../assets/images/menu/postres01.png",
    },
    {
        id: 24,
        category: "postres",
        subcategory: "Carajillos",
        name: "Conejo",
        price: "$109",        
        img: "../assets/images/menu/postres02.png",
    },
    {
        id: 25,
        category: "postres",
        subcategory: "Postres",
        name: "Conejo",
        price: "$95",        
        img: "../assets/images/menu/postres03.png",
    },
    {
        id: 26,
        category: "postres",
        subcategory: "Carajillos",
        name: "Ferrero",
        price: "$119",        
        img: "../assets/images/menu/postres04.png",
    },
    {
        id: 27,
        category: "postres",
        subcategory: "Postres",
        name: "Delicia de chocolate",
        price: "$89",        
        img: "../assets/images/menu/postres05.png",
    },
    {
        id: 28,
        category: "postres",
        subcategory: "Carajillos",
        name: "Licor 43",
        price: "$95",        
        img: "../assets/images/menu/postres06.png",
    },
    {
        id: 27,
        category: "postres",
        subcategory: "Postres",
        name: "Flan",
        price: "$85",        
        img: "../assets/images/menu/postres07.png",
    },
    {
        id: 28,
        category: "postres",
        subcategory: "Carajillos",
        name: "Baileys",
        price: "$89",        
        img: "../assets/images/menu/postres08.png",
    },
    {
        id: 28,
        category: "postres",
        subcategory: "Postres",
        name: "Brownie",
        price: "$99",        
        img: "../assets/images/menu/postres09.png",
    },
]